version: '3'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      timeout: 10s
      retries: 10
      start_period: 10s

  backend:
    build: ./back-end
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=todos
      - DB_HOST=mysql
      - DB_DIALECT=mysql
      - PORT=5000
    ports:
      - 5000:5000
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "
        npm run sequelize &&
        npm start "
  frontend:
    build: ./front-end
    environment:
      - REACT_APP_API_URL=localhost
      - DB_DIALECT=mysql
    ports:
      - 3000:3000
    depends_on:
      - backend